spring:
  output:
    ansi:
      enabled: always

      
#  datasource:
#    url: jdbc:mysql://127.0.0.1:5432
#    driver-class-name: org.postgresql.Driver
#    username: member
#    password: mediscan

  datasource:
    url: jdbc:postgresql://localhost:5432/mediscan
    driver-class-name: org.postgresql.Driver
    username: member
    password: ${custom.datasource.password}
    driver-class-name: org.postgresql.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/mediscan
    username: member
    password: mediscan

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect


  #datasource:
   # url: jdbc:postgresql://localhost:5432/mediscan
    #username: member
    #password: ${custom.datasource.password}
    #driver-class-name: org.postgresql.Driver

  #datasource:
   # url: jdbc:postgresql://localhost:5432/mediscan
    #username: member
    #password: mediscan
    #driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    com.ms.back: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
