spring:
  output:
    ansi:
      enabled: always
      
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      default_batch_fetch_size: 100
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
    show-sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    com.ms.back: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
