server:
  port: 8080

spring:
  application:
    name: MediScan
  profiles:
    active: dev

  config:
    import: optional:application-secret.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: mediscan
    enable:
      jvm: true
      process: true
      http: true
      hikaricp: true
      tomcat: true