spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://mediscan-postgres:5432/mediscan
    username: member
    password: ${custom.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    com.ms.back: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
