spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/mediscan
    username: member
    password: ${custom.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    com.ms.back: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  url:
    back: https://api-sw-pilot.mediscan.site
    front: https://www.mediscan.site

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus,metrics
#  endpoint:
#    prometheus:
#      enabled: true
#  metrics:
#    tags:
#      application: mediscan
#    enable:
#      jvm: true
#      process: true
#      http: true
#      hikaricp: true
#      tomcat: true
